name: Auto Update M3U
on:
  schedule:
    - cron: '0 */6 * * *' # 每 12 小时触发一次
  workflow_dispatch:
jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: doit
        uses: actions/checkout@v2
      - name: Clear existing file
        run: >
          if [ -f bj-unicom-iptv.m3u ]; then
            > bj-unicom-iptv.m3u
          fi
      - name: Get Gist
        run: |
          # 假设你已经安装了 curl 和 jq
          GIST_CONTENT=$(curl -s https://api.github.com/gists/93cf74947770066743fff7c7f4fc5820 | jq -r '.files."bj-unicom-iptv.m3u".content')
          echo "${GIST_CONTENT}"
          # 假设要将 "old_string" 替换为 "new_string"
          OLD_STRING='rtp://'
          NEW_STRING='http://192.168.1.4:8012/rtp/'
          REPLACED_CONTENT="${GIST_CONTENT//$OLD_STRING/$NEW_STRING}"
          echo "${REPLACED_CONTENT}" > bj-unicom-iptv.m3u
          git config --global user.email "kimi@kimi.com"
          git config --global user.name "kimi"
          git add bj-unicom-iptv.m3u
          git commit -m "Updated m3u with replaced strings"
          git push git@github.com:Dendim0n/home-bjunicom-iptv.git main