name: Auto Update M3U
on:
  schedule:
    - cron: '0 */6 * * *' # 每 12 小时触发一次
  workflow_dispatch:
jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: doit
        uses: actions/checkout@v2
      - name: Clear existing file
        run: >
          if [ -f bj-unicom-iptv.m3u ]; then
            > bj-unicom-iptv.m3u
          fi
      - name: Get Gist and Group Channels
        run: |
          # 获取 Gist 内容
          GIST_CONTENT=$(curl -s https://api.github.com/gists/93cf74947770066743fff7c7f4fc5820 | jq -r '.files."bj-unicom-iptv.m3u".content')
          echo "${GIST_CONTENT}"

          # 替换字符串
          OLD_STRING='rtp://'
          NEW_STRING='http://192.168.1.4:8012/rtp/'
          REPLACED_CONTENT="${GIST_CONTENT//$OLD_STRING/$NEW_STRING}"

          # 初始化分组
          HIGH_DEFINITION_GROUP="#EXTM3U\n#EXTINF:-1 group-title=\"高清\",\n"
          OTHER_GROUP="#EXTM3U\n#EXTINF:-1 group-title=\"其他\",\n"

          # 按行处理内容
          while IFS= read -r line; do
            if [[ "$line" == "#EXTINF:-1"* ]]; then
              # 判断是否包含“高清”
              if [[ "$line" == *"高清"* ]]; then
                HIGH_DEFINITION_GROUP+="$line\n"
              else
                OTHER_GROUP+="$line\n"
              fi
            else
              # 非标题行（如 URL）直接追加到当前分组
              if [[ "$line" == "http"* ]]; then
                if [[ "$HIGH_DEFINITION_GROUP" == *"#EXTINF"* ]]; then
                  HIGH_DEFINITION_GROUP+="$line\n"
                else
                  OTHER_GROUP+="$line\n"
                fi
              fi
            fi
          done <<< "$REPLACED_CONTENT"

          # 合并分组内容
          FINAL_CONTENT="$HIGH_DEFINITION_GROUP\n$OTHER_GROUP"
          echo -e "$FINAL_CONTENT" > bj-unicom-iptv.m3u

          # 如果有更改，提交并推送
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "kimi@kimi.com"
            git config --global user.name "kimi"
            git add bj-unicom-iptv.m3u
            git commit -m "Updated m3u with grouped channels"
            git push git@github.com:Dendim0n/home-bjunicom-iptv.git main

            # 版本管理
            git fetch --tags
            VERSION=$(git tag | sort -V | tail -n 1)
            if [ -z "$VERSION" ]; then
              VERSION="v0.0.0"
            fi
            NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++; print}')
            echo ::set-output name=version::$NEW_VERSION
          else
            echo "No changes detected"
          fi

      - name: Create release
        if: steps.get_version.outputs.version != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          
      - name: Upload release asset
        if: steps.get_version.outputs.version != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bj-unicom-iptv.m3u
          asset_name: bj-unicom-iptv.m3u
          asset_content_type: application/x-mpegURL
